site_name: Anchorage Archives
site_url: https://restivesole267.github.io/anchorage-archivist
site_description: Anchorage Archives

repo_name: Anchorage Archivist
repo_url: https://github.com/restivesole267/anchorage-archivist


nav:
  - Home: index.md
  - Judicial:
    - Judicial Index: index.md
    - Cases:
      - Cases Index: index.md
    - Judges:
      - Judges Index: index.md
  - Changelogs:
    - Changelogs Home: index.md
theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list