site_name: Anchorage Archives
theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list